services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - pacto_pela_vida
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - pacto_pela_vida
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - pacto_pela_vida
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  pacto_pela_vida:
    external: true
